### ISSUE TITLE
Better Ui

### ISSUE THREAD

**Issue by moha-b** [mselim7/product-preview-card-component-main#1]
the text was a little bit right and not centered in this link [live site URL](https://mselim7.github.io/product-preview-card-component-main/) not like this image
![](https://github.com/mselim7/product-preview-card-component-main/blob/main/Screenshot.png?raw=true)
for better Ui, u can put it at the bottom of the screen and change the font remove the underlines it will be great

**Comment by mselim7** [comment]
Still working on it to be more responsive for mobile also
